version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: realestate-postgres
    environment:
      POSTGRES_USER: realestate_user
      POSTGRES_PASSWORD: realestate_password
      POSTGRES_DB: realestate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U realestate_user -d realestate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
